### PR TITLE
Update sources.csv to include SNOMED/SCT mapping, and correct LOINC HL7 name

### PR DESCRIPTION
**Pull request by gracepotma**

### CODE REVIEW

**Review by angshu — APPROVED** [review]
Thanks @gracepotma

**Comment by angshu** [comment]
@gracepotma can you please sign the CLA?

**Comment by mohan-13** [comment]
Closing this PR as these changes has been incorporated as part of #196

**Comment by gracepotma** [comment]
I'm so sorry for the delay Angshu; I was travelling to several countries and distracted. I have signed the agreement.

**Pull request closed without merging**
