### PR TITLE
BAH-1782 | Update visit expire hours for auto close visit

### PR DESCRIPTION
**Pull request by SooryaKumaranC-tw**

### CODE REVIEW

**Comment by gsluthra** [comment]
As per this documentation, there is also some SQL mentioned. Is that needed? 
https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3506204/Auto+expiry+of+Visits+in+Bahmni

The value of "0" is fine.

**Comment by SooryaKumaranC-tw** [comment]
> As per this documentation, there is also some SQL mentioned. Is that needed? https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3506204/Auto+expiry+of+Visits+in+Bahmni
> 
> The value of "0" is fine.

Yes it is actually needed. Since initializer liquibase is not working currently not able to implement it. I will create a separate card to track this.

**Comment by gsluthra** [comment]
In that case, isn't this card BLOCKED? How will QA verify this card if its half-done?

**Comment by gsluthra** [comment]
I will merge this PR.. since this is good.

**Pull request merged**
